# .prettierrc.toml
printWidth = 80
tabWidth = 4
useTabs = true
semi = false
singleQuote = false
jsxSingleQuote = false
trailingComma = "es5"
bracketSpacing = true
bracketSameLine = false
arrowParens = "always"
proseWrap = "preserve"
endOfLine = "lf"
