# metadata (pretty self-explanatory)
# doesn't do anything functionally, just looks cool :P
[meta]
name = "My Application"
description = "Very cool application"
version = "1.0"

# executable data
[exec]
# binary name/path, %variables% or @appname
# bin = "bash"
# command-line arguments
# you must include "%!" in the arguments list where you want all the command-line arguments (and/or derivative applications' arguments) to go to.
args = ["%!"]

# environment variables for this application.
# example:
# MANGOHUD = 1
[env]
